[package]
name = "venture/universal-systems"

version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.2"
Cmdr = "evaera/cmdr@1.12.0"

[dependencies]
debugLoggerUtil = "bubshurb/debugloggerutil@1.0.0"
Component = "bubshurb/component@1.0.0"
Signal = "kineticwallet/lemon-signal@1.10.0"
contextActionServiceUtil = "bubshurb/contextactionserviceutil@1.0.0"
Zone = "mattschrubb/zoneplus@3.2.0"
network = "bubshurb/network@1.6.0"
loader = "sleitnick/loader@2.0.0"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.1.0"
Sift = "csqrl/sift@0.0.8"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
Icon = "m-ethods/topbarplus@3.0.5"
Input = "sleitnick/input@2.3.0"
reflex = "littensy/react-reflex@0.3.5"
spr = "blackjackiee/spr@1.1.3"
partcache = "4igz/partcache@1.0.1"
camerashaker = "brittonfischer/camerashaker@0.1.0"