local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

return {
	tenFloors = {
		id = 2697043460,
	},
	fiftyFloors = {
		id = 2697043455,
	},
	buyCircusCannon = {
		id = 1051314279,
		cannonName = "circusCannon",
	},
	buyArtillery = {
		id = 1136518787,
		cannonName = "artillery",
	},
	buyRailgun = {
		id = 1035960145,
		cannonName = "railgun",
	},
	buyVIP = {
		id = 1022963419,
	},
	newCannon = {
		id = 2697043453,
	},
	buyDoubleDistance = {
		id = 1022787535, -- 2x Distance
	},

	buyDoubleMoney = {
		id = 1022657721, -- 2x Money
	},
}
