local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

return {
	tenFloors = {
		id = 2697043460,
	},
	fiftyFloors = {
		id = 2697043455,
	},
	buyCircusCannon = {
		id = 1051314279,
	},
	buyArmyCannon = {
		id = 1051600321,
	},
	buyArtillery = {
		id = 1028783141,
	},
	buyRailgun = {
		id = 1035960145,
	},
	buyVIP = {
		id = 1060138098,
	},
	newCannon = {
		id = 2697043453,
	},
}
