return {
	cannonTiers = {
		{
			id = 2691911191, -- Cannon Upgrade 1
			power = math.pow(1.25, 1),
			tier = 1,
		},
		{
			id = 2691911290, -- Cannon Upgrade 2
			power = math.pow(1.25, 2),
			tier = 2,
		},
		{
			id = 2691911406, -- Cannon Upgrade 3
			power = math.pow(1.25, 3),
			tier = 3,
		},
		{
			id = 3101580073, -- Cannon Upgrade 4
			power = math.pow(1.25, 4),
			tier = 4,
		},
		{
			id = 2691911536, -- Cannon Upgrade 5
			power = math.pow(1.25, 5),
			tier = 5,
		},
	},
}
